using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AnalyzerProject.SourceGeneration;

[Generator]
public class SimpleSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
        {
            var source = GenerateSource();
            spc.AddSource("GeneratedSimple.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace GeneratedNamespace;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedSimple");
        sb.AppendLine("{");
        sb.AppendLine("    public static string TestProperty => \"Hello from generated code\";");
        sb.AppendLine("}");
        return sb.ToString();
    }
}